apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: devfile-java
  namespace: karthik
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: devfile-java
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: devfile-java-
      labels:
        build.appstudio.openshift.io/application: test-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: devfile-java
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: karthik
    spec:
      params:
      - name: git-url
        value: https://github.com/karthikjeeyar/devfile-java
      - name: output-image
        value: quay.io/karthik_jk/devfile-java:latest-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: devfile-java/$(tt.params.git-revision)
    status: {}
status: {}
